
package acs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IQsFundService", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IQsFundService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.AccountDataBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSubject", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAccountSubject")
    @ResponseWrapper(localName = "getAccountSubjectResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAccountSubjectResponse")
    public List<AccountDataBean> getAccountSubject(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns acs.YssResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendOrgInfo", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendOrgInfo")
    @ResponseWrapper(localName = "sendOrgInfoResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendOrgInfoResponse")
    public YssResponse sendOrgInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<OrgInfo> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.BankBondBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBondData", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetBankBondData")
    @ResponseWrapper(localName = "getBankBondDataResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetBankBondDataResponse")
    public List<BankBondBean> getBankBondData(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns acs.YssResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pushAssetAccount", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.PushAssetAccount")
    @ResponseWrapper(localName = "pushAssetAccountResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.PushAssetAccountResponse")
    public YssResponse pushAssetAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<AssetAccount> arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.InvestBalanceBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvestBalance", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetInvestBalance")
    @ResponseWrapper(localName = "getInvestBalanceResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetInvestBalanceResponse")
    public List<InvestBalanceBean> getInvestBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.SubjectBalanceDataBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubjectBalance", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetSubjectBalance")
    @ResponseWrapper(localName = "getSubjectBalanceResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetSubjectBalanceResponse")
    public List<SubjectBalanceDataBean> getSubjectBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.TransferAmountBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransferAmount", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetTransferAmount")
    @ResponseWrapper(localName = "getTransferAmountResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetTransferAmountResponse")
    public List<TransferAmountBean> getTransferAmount(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.ExchangeDataBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExchangeData", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetExchangeData")
    @ResponseWrapper(localName = "getExchangeDataResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetExchangeDataResponse")
    public List<ExchangeDataBean> getExchangeData(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.InterestRecBalBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInterestRecBal", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetInterestRecBal")
    @ResponseWrapper(localName = "getInterestRecBalResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetInterestRecBalResponse")
    public List<InterestRecBalBean> getInterestRecBal(
        @WebParam(name = "arg0", targetNamespace = "")
        List<InterestRecBalBean> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.AccountBalanceBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalance", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAccountBalance")
    @ResponseWrapper(localName = "getAccountBalanceResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAccountBalanceResponse")
    public List<AccountBalanceBean> getAccountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.WarrantLiquidateBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWarrantLiquidateData", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetWarrantLiquidateData")
    @ResponseWrapper(localName = "getWarrantLiquidateDataResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetWarrantLiquidateDataResponse")
    public List<WarrantLiquidateBean> getWarrantLiquidateData(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.util.List<acs.AssetDataBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssetData", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAssetData")
    @ResponseWrapper(localName = "getAssetDataResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetAssetDataResponse")
    public List<AssetDataBean> getAssetData();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns acs.YssResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendAccountSealInfo", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendAccountSealInfo")
    @ResponseWrapper(localName = "sendAccountSealInfoResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendAccountSealInfoResponse")
    public YssResponse sendAccountSealInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<AccountSealInfo> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns acs.YssResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSeatInfo", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendSeatInfo")
    @ResponseWrapper(localName = "sendSeatInfoResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendSeatInfoResponse")
    public YssResponse sendSeatInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<SeatInfo> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns acs.YssResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendShareHolderInfo", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendShareHolderInfo")
    @ResponseWrapper(localName = "sendShareHolderInfoResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendShareHolderInfoResponse")
    public YssResponse sendShareHolderInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<ShareHolderInfo> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<acs.HkFengKongDataBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHkData", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetHkData")
    @ResponseWrapper(localName = "getHkDataResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetHkDataResponse")
    public List<HkFengKongDataBean> getHkData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.ShareHolderCheck>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShareHolderCheck", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetShareHolderCheck")
    @ResponseWrapper(localName = "getShareHolderCheckResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetShareHolderCheckResponse")
    public List<ShareHolderCheck> getShareHolderCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.CwjySj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCwjysj", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetCwjysj")
    @ResponseWrapper(localName = "getCwjysjResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetCwjysjResponse")
    public List<CwjySj> getCwjysj(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.FeeDetailBean>
     * @throws YssException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFeeDetail", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetFeeDetail")
    @ResponseWrapper(localName = "getFeeDetailResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetFeeDetailResponse")
    public List<FeeDetailBean> getFeeDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws YssException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.SubjectAccrualBean>
     * @throws YssException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKmfsBalance", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetKmfsBalance")
    @ResponseWrapper(localName = "getKmfsBalanceResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetKmfsBalanceResponse")
    public List<SubjectAccrualBean> getKmfsBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws YssException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.SubjectAmountBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubjectAmount", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetSubjectAmount")
    @ResponseWrapper(localName = "getSubjectAmountResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetSubjectAmountResponse")
    public List<SubjectAmountBean> getSubjectAmount(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws YssException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendProductInfo", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendProductInfo")
    @ResponseWrapper(localName = "sendProductInfoResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SendProductInfoResponse")
    public String sendProductInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        ProductInfoBean arg0)
        throws YssException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns acs.Message
     * @throws YssException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synchroProduct", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SynchroProduct")
    @ResponseWrapper(localName = "synchroProductResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.SynchroProductResponse")
    public Message synchroProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0)
        throws YssException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGzfyjtxx", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetGzfyjtxx")
    @ResponseWrapper(localName = "getGzfyjtxxResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetGzfyjtxxResponse")
    public String getGzfyjtxx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<acs.TotalAssets>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalAssets", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetTotalAssets")
    @ResponseWrapper(localName = "getTotalAssetsResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.GetTotalAssetsResponse")
    public List<TotalAssets> getTotalAssets(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "pushDataForCheck", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.PushDataForCheck")
    @ResponseWrapper(localName = "pushDataForCheckResponse", targetNamespace = "http://qsfund.service.webservice.fa.yss.com/", className = "acs.PushDataForCheckResponse")
    public void pushDataForCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        List<QsDataForCheck> arg0);

}
