
package acs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "YssFundForQsFundservice", targetNamespace = "http://qsfund.service.webservice.fa.yss.com", wsdlLocation = "http://192.168.99.40:7001/fundacc20190630001/YssFundForQSService?wsdl")
public class YssFundForQsFundservice
    extends Service
{

    private final static URL YSSFUNDFORQSFUNDSERVICE_WSDL_LOCATION;
    private final static WebServiceException YSSFUNDFORQSFUNDSERVICE_EXCEPTION;
    private final static QName YSSFUNDFORQSFUNDSERVICE_QNAME = new QName("http://qsfund.service.webservice.fa.yss.com", "YssFundForQsFundservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.99.40:7001/fundacc20190630001/YssFundForQSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YSSFUNDFORQSFUNDSERVICE_WSDL_LOCATION = url;
        YSSFUNDFORQSFUNDSERVICE_EXCEPTION = e;
    }

    public YssFundForQsFundservice() {
        super(__getWsdlLocation(), YSSFUNDFORQSFUNDSERVICE_QNAME);
    }

    public YssFundForQsFundservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), YSSFUNDFORQSFUNDSERVICE_QNAME, features);
    }

    public YssFundForQsFundservice(URL wsdlLocation) {
        super(wsdlLocation, YSSFUNDFORQSFUNDSERVICE_QNAME);
    }

    public YssFundForQsFundservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YSSFUNDFORQSFUNDSERVICE_QNAME, features);
    }

    public YssFundForQsFundservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YssFundForQsFundservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IQsFundService
     */
    @WebEndpoint(name = "YssFundForQsFundServer")
    public IQsFundService getYssFundForQsFundServer() {
        return super.getPort(new QName("http://qsfund.service.webservice.fa.yss.com", "YssFundForQsFundServer"), IQsFundService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IQsFundService
     */
    @WebEndpoint(name = "YssFundForQsFundServer")
    public IQsFundService getYssFundForQsFundServer(WebServiceFeature... features) {
        return super.getPort(new QName("http://qsfund.service.webservice.fa.yss.com", "YssFundForQsFundServer"), IQsFundService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YSSFUNDFORQSFUNDSERVICE_EXCEPTION!= null) {
            throw YSSFUNDFORQSFUNDSERVICE_EXCEPTION;
        }
        return YSSFUNDFORQSFUNDSERVICE_WSDL_LOCATION;
    }

}
